inherits = "melange"
# inherits = "rose_pine_moon"
# inherits = "catppuccin_macchiato"
# inherits = "tokyonight"
# inherits = "nord-night"
# inherits = "gruvbox_dark_hard"
# inherits = "test"

"ui.background" = { bg = "none" }
"ui.popup" = { bg = "none" }
"ui.popup.info" = { bg = "none" }
"ui.bufferline.background" = { bg = "none" }
"ui.bufferline" = { bg = "none" }
"ui.statusline" = { bg = "none" }
"ui.text" = { bg = "none" }
"ui.menu" = { bg = "none" }

"ui.gutter" = { bg = "none" }
"ui.linenr" = { bg = "none" }
